name: Minify JS and CSS

on:
  push:
    branches: [ main ] # Or your target branch
    paths:
      - 'website/squad/assets/js/**'
      - 'website/squad/assets/css/**'
      - 'minify.js'
      - 'package.json'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or whatever version you prefer

      - name: Install dependencies
        run: npm install

      - name: Run Minifier Script
        run: node tenser-minify.js

      # Optional: Commit and push minified files
      - name: Commit minified files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-minified JS and CSS"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
