name: Minify JS and CSS

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull requests for any branch
    paths:
      - 'website/squad/assets/js/**'
      - 'website/squad/assets/css/**'
      - 'minify.js'
      - 'package.json'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensures push works using GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Minifier Script
        run: node minify.js

      - name: Commit and push minified files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-minified JS and CSS"
          git push
